* About

There are two keyboard layouts in this repo. One for X11/XKB and one for KBD.
XKB is the one you would usually want.
KBD is for ttys and terminals without graphics.

The keyboard layout is based on the US layout, but with some special keys:

- Swedish åäö on =Lv3+[';=
- German üß on =Lv3+us=
- UK £ on =Lv3+3=
- EU € on =Lv3+e=
- Cyrillic alphabet on =Group2= (Not included in KBD variant)
- Caps Lock as Control (=Control_L=)


- Level 3 chooser is Alt-Gr (=Alt_R=)
- Groups are changed with both left and right Controls (goes up or
  down in group list depending on which one is pressed first) (Not included in KBD variant)

* How to install the layout under XKB

1. Add the file ~seba.x11~ to ~~/xkb/symbols/~

#+BEGIN_SRC sh
  mkdir -p ~/.config/xkb/symbols && ln -s `pwd`/seba.x11 ~/.config/xkb/symbols/seba
#+END_SRC

2. Add the file ~evdev.xml~ to ~~/xkb/rules/~
#+BEGIN_SRC sh
  mkdir -p ~/.config/xkb/rules && ln -s `pwd`/evdev.xml ~/.config/xkb/rules/
#+END_SRC

3. Logout + login.

4. Set Seba keyboard layout

#+BEGIN_SRC sh
  setxkbmap -layout seba
#+END_SRC

* How to install the layout (keymap) under KBD

1. Copy ~seba.kbd~ to ~/usr/local/share/kbd/keymaps~

#+BEGIN_SRC sh
  mkdir -p /usr/local/share/kbd/keymaps && ln -s `pwd`/seba.kbd /usr/local/share/kbd/keymaps/seba
#+END_SRC

2a. Testing it out

#+BEGIN_SRC sh
  loadkeys /usr/local/share/kbd/keymaps/seba
#+END_SRC

2b. For persistent usage

#+BEGIN_SRC sh
  localectl set-keymap --no-convert /usr/local/share/kbd/keymaps/seba
#+END_SRC

* Resources

[[https://linux.die.net/man/5/keymaps][man keymaps]]
[[https://linux.die.net/man/7/xkeyboard-config][man xkeyboard-config]]
